# Generated by Django 5.0.6 on 2026-07-09 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriKI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('deskripsi', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Kategori KI',
                'verbose_name_plural': 'Kategori KI',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='DokumenResmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('file_asli', models.FileField(blank=True, null=True, upload_to='knowledge/dokumen/')),
                ('teks_lengkap', models.TextField(blank=True, help_text='Teks bersih hasil ekstraksi dari file_asli, sumber untuk proses chunking/RAG.')),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('diupload_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokumen_diupload', to=settings.AUTH_USER_MODEL)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokumen', to='knowledge.kategoriki')),
            ],
            options={
                'verbose_name': 'Dokumen Resmi',
                'verbose_name_plural': 'Dokumen Resmi',
                'ordering': ['-tanggal_upload'],
            },
        ),
        migrations.CreateModel(
            name='ChunkEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_potongan', models.TextField()),
                ('urutan', models.PositiveIntegerField(help_text='Urutan chunk ini dalam dokumen asal (dimulai dari 0 atau 1).')),
                ('vector_id', models.CharField(help_text='ID record yang bersangkutan di ChromaDB (bukan vector-nya sendiri).', max_length=255, unique=True)),
                ('dokumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.dokumenresmi')),
            ],
            options={
                'verbose_name': 'Chunk Embedding',
                'verbose_name_plural': 'Chunk Embedding',
                'ordering': ['dokumen', 'urutan'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.CharField(max_length=500)),
                ('jawaban', models.TextField()),
                ('jumlah_dilihat', models.PositiveIntegerField(default=0)),
                ('rating_membantu', models.PositiveIntegerField(default=0, help_text='Jumlah pengguna yang menandai FAQ ini membantu.')),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq', to='knowledge.kategoriki')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['-jumlah_dilihat'],
            },
        ),
        migrations.AddConstraint(
            model_name='chunkembedding',
            constraint=models.UniqueConstraint(fields=('dokumen', 'urutan'), name='unik_urutan_per_dokumen'),
        ),
    ]
