# Generated by Django 5.0.6 on 2026-07-13 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumenresmi',
            name='divalidasi_oleh',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokumen_divalidasi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dokumenresmi',
            name='divalidasi_pada',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='dokumenresmi',
            name='status_validasi',
            field=models.CharField(choices=[('draf', 'Draf / belum diverifikasi'), ('terverifikasi', 'Terverifikasi'), ('dinonaktifkan', 'Dinonaktifkan')], db_index=True, default='draf', help_text='Hanya dokumen terverifikasi yang digunakan oleh chatbot.', max_length=20),
        ),
        migrations.AddField(
            model_name='dokumenresmi',
            name='sumber_url',
            field=models.URLField(blank=True, help_text='Tautan halaman resmi asal dokumen, bila tersedia.'),
        ),
    ]
