# Generated by Django 5.0.6 on 2026-07-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_dokumenresmi_divalidasi_oleh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumenresmi',
            name='indexing_dimulai_pada',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='dokumenresmi',
            name='indexing_selesai_pada',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='dokumenresmi',
            name='jumlah_halaman',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='dokumenresmi',
            name='pesan_indexing',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='dokumenresmi',
            name='status_indexing',
            field=models.CharField(choices=[('belum', 'Belum dijadwalkan'), ('menunggu', 'Menunggu diproses'), ('diproses', 'Sedang diproses'), ('berhasil', 'Berhasil'), ('gagal', 'Gagal')], db_index=True, default='belum', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='dokumenresmi',
            name='ukuran_file',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
