# Generated by Django 5.0.6 on 2026-07-18 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def verifikasi_faq_internal_yang_sudah_ada(apps, schema_editor):
    FAQ = apps.get_model('knowledge', 'FAQ')
    FAQ.objects.filter(sumber_url='').update(
        status_validasi='terverifikasi',
        status_indexing='menunggu',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_initialize_document_indexing_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SinkronisasiFAQLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumber_url', models.URLField()),
                ('status', models.CharField(choices=[('berjalan', 'Berjalan'), ('berhasil', 'Berhasil'), ('gagal', 'Gagal')], default='berjalan', max_length=20)),
                ('jumlah_halaman', models.PositiveIntegerField(default=0)),
                ('jumlah_ditemukan', models.PositiveIntegerField(default=0)),
                ('jumlah_baru', models.PositiveIntegerField(default=0)),
                ('jumlah_diperbarui', models.PositiveIntegerField(default=0)),
                ('jumlah_dinonaktifkan', models.PositiveIntegerField(default=0)),
                ('pesan', models.TextField(blank=True)),
                ('dimulai_pada', models.DateTimeField(auto_now_add=True)),
                ('selesai_pada', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log Sinkronisasi FAQ DJKI',
                'verbose_name_plural': 'Log Sinkronisasi FAQ DJKI',
                'ordering': ['-dimulai_pada'],
            },
        ),
        migrations.AddField(
            model_name='faq',
            name='aktif_sumber',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='diindeks_pada',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='divalidasi_oleh',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_divalidasi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faq',
            name='divalidasi_pada',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='hash_konten',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='faq',
            name='pesan_indexing',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='faq',
            name='sinkronisasi_pada',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='status_indexing',
            field=models.CharField(choices=[('belum', 'Belum diindeks'), ('menunggu', 'Menunggu diproses'), ('diproses', 'Sedang diproses'), ('berhasil', 'Berhasil'), ('gagal', 'Gagal')], db_index=True, default='belum', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='faq',
            name='status_validasi',
            field=models.CharField(choices=[('draf', 'Draf / belum diverifikasi'), ('terverifikasi', 'Terverifikasi'), ('dinonaktifkan', 'Dinonaktifkan')], db_index=True, default='draf', help_text='FAQ hasil sinkronisasi wajib diverifikasi sebelum digunakan chatbot.', max_length=20),
        ),
        migrations.AddField(
            model_name='faq',
            name='subkategori_sumber',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='faq',
            name='sumber_kunci',
            field=models.CharField(blank=True, editable=False, help_text='Identitas stabil pertanyaan dari sumber eksternal.', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='sumber_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='vector_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(
            verifikasi_faq_internal_yang_sudah_ada,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['status_validasi', 'aktif_sumber'], name='knowledge_f_status__88608c_idx'),
        ),
    ]
