# Generated by Django 5.0.6 on 2026-07-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PercakapanChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.TextField()),
                ('jawaban', models.TextField()),
                ('sumber_dokumen', models.JSONField(blank=True, default=list, help_text='Daftar dokumen/FAQ yang disitasi AI untuk menyusun jawaban ini.')),
                ('confidence_score', models.FloatField(blank=True, help_text='Skor keyakinan model AI terhadap jawaban (0.0 - 1.0).', null=True)),
                ('dieskalasi', models.BooleanField(default=False, help_text='True jika percakapan ini perlu ditindaklanjuti oleh petugas manusia.')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('rating_membantu', models.BooleanField(blank=True, help_text='Feedback pengguna: True = membantu, False = tidak membantu, null = belum ada feedback.', null=True)),
            ],
            options={
                'verbose_name': 'Percakapan Chatbot',
                'verbose_name_plural': 'Percakapan Chatbot',
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
