# Generated by Django 5.0.6 on 2026-07-18 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def queue_existing_escalations(apps, schema_editor):
    PercakapanChatbot = apps.get_model('chatbot', 'PercakapanChatbot')
    PercakapanChatbot.objects.filter(dieskalasi=True).update(status_tindak_lanjut='menunggu')


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='percakapanchatbot',
            name='catatan_tindak_lanjut',
            field=models.TextField(blank=True, help_text='Catatan internal petugas; tidak ditampilkan kepada pengguna publik.'),
        ),
        migrations.AddField(
            model_name='percakapanchatbot',
            name='dikoreksi_oleh',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='konsultasi_dikoreksi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='percakapanchatbot',
            name='dikoreksi_pada',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='percakapanchatbot',
            name='diselesaikan_pada',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='percakapanchatbot',
            name='ditinjau_pada',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='percakapanchatbot',
            name='ditugaskan_kepada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='konsultasi_ditugaskan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='percakapanchatbot',
            name='jawaban_koreksi',
            field=models.TextField(blank=True, help_text='Koreksi petugas bila jawaban sistem perlu diperbaiki.'),
        ),
        migrations.AddField(
            model_name='percakapanchatbot',
            name='status_tindak_lanjut',
            field=models.CharField(choices=[('tidak_perlu', 'Tidak perlu eskalasi'), ('menunggu', 'Menunggu ditinjau petugas'), ('diproses', 'Sedang ditangani'), ('selesai', 'Selesai ditindaklanjuti')], db_index=True, default='tidak_perlu', max_length=20),
        ),
        migrations.RunPython(queue_existing_escalations, migrations.RunPython.noop),
    ]
