# Generated by Django 5.0.6 on 2026-07-18 15:05

import django.db.models.deletion
from datetime import timedelta
from django.conf import settings
from django.db import migrations, models


def isi_sla_eskalasi_lama(apps, schema_editor):
    Percakapan = apps.get_model('chatbot', 'PercakapanChatbot')
    for item in Percakapan.objects.filter(dieskalasi=True, batas_tindak_lanjut__isnull=True).iterator():
        item.batas_tindak_lanjut = item.dibuat_pada + timedelta(hours=24)
        item.save(update_fields=['batas_tindak_lanjut'])


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_percakapanchatbot_catatan_tindak_lanjut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='percakapanchatbot',
            name='batas_tindak_lanjut',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='percakapanchatbot',
            name='prioritas',
            field=models.CharField(choices=[('normal', 'Normal'), ('tinggi', 'Tinggi'), ('mendesak', 'Mendesak')], db_index=True, default='normal', max_length=12),
        ),
        migrations.RunPython(isi_sla_eskalasi_lama, migrations.RunPython.noop),
        migrations.CreateModel(
            name='TindakLanjutKonsultasiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_sebelum', models.CharField(choices=[('tidak_perlu', 'Tidak perlu eskalasi'), ('menunggu', 'Menunggu ditinjau petugas'), ('diproses', 'Sedang ditangani'), ('selesai', 'Selesai ditindaklanjuti')], max_length=20)),
                ('status_sesudah', models.CharField(choices=[('tidak_perlu', 'Tidak perlu eskalasi'), ('menunggu', 'Menunggu ditinjau petugas'), ('diproses', 'Sedang ditangani'), ('selesai', 'Selesai ditindaklanjuti')], max_length=20)),
                ('catatan', models.TextField(blank=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('percakapan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_tindak_lanjut', to='chatbot.percakapanchatbot')),
                ('petugas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jejak Tindak Lanjut Konsultasi',
                'verbose_name_plural': 'Jejak Tindak Lanjut Konsultasi',
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
