# Generated by Django 5.0.6 on 2026-08-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_percakapanchatbot_pelacakan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='percakapanchatbot',
            name='email_pengguna',
            field=models.EmailField(blank=True, help_text='Opsional. Dipakai hanya untuk pemberitahuan status konsultasi.', max_length=254),
        ),
    ]
