# Generated by Django 5.0.6 on 2026-07-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CekMerekLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_merek_diajukan', models.CharField(max_length=255)),
                ('deskripsi_produk', models.TextField(blank=True)),
                ('kelas_nice_terdeteksi', models.CharField(blank=True, help_text='Kelas Nice hasil deteksi otomatis (mis. dari deskripsi produk).', max_length=10)),
                ('skor_risiko', models.CharField(choices=[('rendah', 'Rendah'), ('sedang', 'Sedang'), ('tinggi', 'Tinggi')], max_length=10)),
                ('hasil_lengkap', models.JSONField(blank=True, default=dict, help_text='Detail lengkap hasil pengecekan (mis. daftar merek mirip beserta skornya).')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('ip_pengguna', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log Cek Merek',
                'verbose_name_plural': 'Log Cek Merek',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='MirrorPDKI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_merek', models.CharField(max_length=255)),
                ('kelas_nice', models.CharField(help_text='Kelas Nice Classification, mis: 25, 35.', max_length=10)),
                ('status', models.CharField(choices=[('terdaftar', 'Terdaftar'), ('diajukan', 'Dalam Proses Pengajuan'), ('ditolak', 'Ditolak'), ('kedaluwarsa', 'Kedaluwarsa')], default='diajukan', max_length=20)),
                ('pemilik', models.CharField(max_length=255)),
                ('tanggal_daftar', models.DateField(blank=True, null=True)),
                ('tanggal_sinkron_terakhir', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mirror PDKI',
                'verbose_name_plural': 'Mirror PDKI',
                'ordering': ['nama_merek'],
                'indexes': [models.Index(fields=['nama_merek'], name='trademark_m_nama_me_21c352_idx'), models.Index(fields=['kelas_nice'], name='trademark_m_kelas_n_2619b8_idx')],
            },
        ),
    ]
