# Generated by Django 5.0.6 on 2026-07-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mirrorpdki',
            name='label_merek',
            field=models.ImageField(blank=True, help_text='Etiket/logo referensi dari sumber resmi PDKI (PNG/JPEG).', null=True, upload_to='trademark/referensi/'),
        ),
        migrations.AddField(
            model_name='mirrorpdki',
            name='sumber_label_url',
            field=models.URLField(blank=True, help_text='Tautan halaman PDKI resmi tempat etiket referensi diverifikasi.'),
        ),
        migrations.AddField(
            model_name='mirrorpdki',
            name='visual_embedding',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name='mirrorpdki',
            name='visual_embedding_diperbarui',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
