# Generated by Django 5.0.6 on 2026-07-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademark', '0002_mirrorpdki_label_merek_mirrorpdki_sumber_label_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinkronisasiPDKILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumber', models.CharField(default='brm_djki', max_length=30)),
                ('sumber_url', models.URLField(unique=True)),
                ('judul_sumber', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('berjalan', 'Berjalan'), ('berhasil', 'Berhasil'), ('gagal', 'Gagal'), ('dilewati', 'Dilewati')], default='berjalan', max_length=20)),
                ('jumlah_ditemukan', models.PositiveIntegerField(default=0)),
                ('jumlah_baru', models.PositiveIntegerField(default=0)),
                ('jumlah_diperbarui', models.PositiveIntegerField(default=0)),
                ('pesan', models.TextField(blank=True)),
                ('dimulai_pada', models.DateTimeField(auto_now_add=True)),
                ('selesai_pada', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log Sinkronisasi Data Merek',
                'verbose_name_plural': 'Log Sinkronisasi Data Merek',
                'ordering': ['-dimulai_pada'],
            },
        ),
        migrations.AddField(
            model_name='mirrorpdki',
            name='nomor_permohonan',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mirrorpdki',
            name='sumber_data',
            field=models.CharField(choices=[('manual', 'Input manual petugas'), ('brm_djki', 'Berita Resmi Merek DJKI'), ('api_pdki', 'API resmi PDKI'), ('demo', 'Data demonstrasi')], db_index=True, default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='mirrorpdki',
            name='sumber_data_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='mirrorpdki',
            name='tanggal_penerimaan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mirrorpdki',
            name='tanggal_publikasi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='mirrorpdki',
            constraint=models.UniqueConstraint(condition=models.Q(('nomor_permohonan', ''), _negated=True), fields=('nomor_permohonan', 'kelas_nice'), name='unik_permohonan_kelas_mirror_pdki'),
        ),
    ]
