# Generated by Django 5.0.6 on 2026-07-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademark', '0003_sinkronisasipdkilog_mirrorpdki_nomor_permohonan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiceClassificationTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.CharField(db_index=True, max_length=2)),
                ('basic_number', models.CharField(db_index=True, max_length=12)),
                ('indication_en', models.CharField(max_length=700)),
                ('synonyms_en', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('wipo', 'WIPO Nice Classification'), ('skm_djki', 'SKM DJKI')], default='wipo', max_length=20)),
                ('version', models.CharField(db_index=True, max_length=20)),
                ('effective_date', models.DateField()),
                ('source_url', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Istilah Klasifikasi Nice',
                'verbose_name_plural': 'Istilah Klasifikasi Nice',
                'ordering': ['class_number', 'basic_number'],
                'indexes': [models.Index(fields=['source', 'version', 'class_number'], name='trademark_n_source_40cf66_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='niceclassificationterm',
            constraint=models.UniqueConstraint(fields=('source', 'version', 'basic_number'), name='unique_nice_term_source_version_basic_number'),
        ),
    ]
