# Generated by Django 5.0.6 on 2026-07-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademark', '0004_niceclassificationterm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cekmereklog',
            name='ip_pengguna',
        ),
        migrations.AddField(
            model_name='cekmereklog',
            name='ip_hash',
            field=models.CharField(blank=True, editable=False, help_text='Sidik anonim untuk mitigasi penyalahgunaan; alamat IP asli tidak disimpan.', max_length=64),
        ),
    ]
