# Generated by Django 5.0.6 on 2026-07-16 14:12

from django.db import migrations, models


CURRENT_NAME = 'Kantor Wilayah Kementerian Hukum Nusa Tenggara Barat'


def update_obsolete_unit_names(apps, schema_editor):
    profile = apps.get_model('core', 'UserProfile')
    profile.objects.filter(
        unit_kerja__in=['Kanwil Kemenkum NTB', 'Kanwil Kemenkumham NTB'],
    ).update(unit_kerja=CURRENT_NAME)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='unit_kerja',
            field=models.CharField(blank=True, default='Kantor Wilayah Kementerian Hukum Nusa Tenggara Barat', max_length=150),
        ),
        migrations.RunPython(update_obsolete_unit_names, migrations.RunPython.noop),
    ]
