# Generated by Django 5.0.6 on 2026-07-18 15:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_unit_kerja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UjiCobaPengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_respons', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('peran', models.CharField(choices=[('masyarakat', 'Masyarakat/pemohon'), ('umkm', 'Pelaku UMKM'), ('petugas', 'Petugas layanan'), ('lainnya', 'Lainnya')], max_length=20)),
                ('layanan', models.CharField(choices=[('keseluruhan', 'Keseluruhan portal'), ('chatbot', 'Chatbot Helpdesk KI'), ('cek_merek', 'Penelusuran awal merek'), ('checklist', 'Checklist dokumen'), ('informasi', 'Pusat informasi')], max_length=20)),
                ('tugas_berhasil', models.BooleanField()),
                ('kemudahan', models.PositiveSmallIntegerField()),
                ('kejelasan', models.PositiveSmallIntegerField()),
                ('kepercayaan', models.PositiveSmallIntegerField()),
                ('kepuasan', models.PositiveSmallIntegerField()),
                ('masukan', models.TextField(blank=True)),
                ('persetujuan', models.BooleanField(default=False)),
                ('ip_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hasil Uji Coba Pengguna',
                'verbose_name_plural': 'Hasil Uji Coba Pengguna',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_mulai', models.DateField()),
                ('periode_selesai', models.DateField()),
                ('metrik', models.JSONField(default=dict, editable=False)),
                ('catatan', models.TextField(blank=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_monitoring_dibuat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Snapshot Monitoring',
                'verbose_name_plural': 'Snapshot Monitoring',
                'ordering': ['-periode_selesai', '-dibuat_pada'],
            },
        ),
        migrations.AddConstraint(
            model_name='monitoringsnapshot',
            constraint=models.CheckConstraint(check=models.Q(('periode_selesai__gte', models.F('periode_mulai'))), name='monitoring_periode_valid'),
        ),
    ]
