# Generated by Django 5.0.6 on 2026-08-05 13:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ujicobapengguna_layanan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Tambah'), ('update', 'Ubah'), ('delete', 'Hapus')], max_length=12)),
                ('model_label', models.CharField(db_index=True, max_length=160)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('object_repr', models.CharField(max_length=500)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log Admin',
                'verbose_name_plural': 'Audit Log Admin',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlaNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_id', models.UUIDField(db_index=True)),
                ('message', models.CharField(max_length=500)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['read_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('chatbot_ai', 'Jawaban Chatbot AI'), ('classification_ai', 'Klasifikasi Kelas AI'), ('trademark_ai', 'Penelusuran Merek AI'), ('document_index', 'Indexing Dokumen'), ('faq_index', 'Indexing FAQ'), ('brm_enrich', 'Pengayaan BRM DJKI')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Menunggu'), ('running', 'Sedang diproses'), ('succeeded', 'Berhasil'), ('failed', 'Gagal')], db_index=True, default='queued', max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_jobs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'available_at'], name='core_backgr_status_93f877_idx'), models.Index(fields=['kind', 'status'], name='core_backgr_kind_e581f6_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='slanotification',
            constraint=models.UniqueConstraint(fields=('recipient', 'consultation_id'), name='unique_sla_notification_recipient_consultation'),
        ),
    ]
