# Generated by Django 5.0.6 on 2026-08-25 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_adminauditlog_slanotification_backgroundjob_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalConfiguration',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('ai_cek_merek_aktif', models.BooleanField(default=False, help_text='Aktifkan hanya jika data pembanding dan prosedur peninjauan sudah siap.')),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('diperbarui_oleh', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='konfigurasi_portal_diperbarui', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Konfigurasi Portal',
                'verbose_name_plural': 'Konfigurasi Portal',
            },
        ),
    ]
